#!/usr/bin/env python3
"""
Diffie-Hellman Key Exchange Simulator & Educational Visualizer

This tool simulates the Diffie-Hellman key exchange protocol step-by-step.
It is designed to explain the mathematics and concepts behind public-key cryptography
and demonstrate why an eavesdropper (Eve) cannot easily compute the shared secret.
"""

import sys
import argparse
import random
import time
from typing import Tuple, List

# ANSI Color Escape Codes
CYAN = "\033[96m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
MAGENTA = "\033[95m"
BOLD = "\033[1m"
RESET = "\033[0m"

def colored(text: str, color_code: str) -> str:
    """Wrap text with ANSI color code if supported by platform."""
    if sys.platform == "win32":
        # Enable virtual terminal processing on Windows if possible
        import os
        os.system("")
    return f"{color_code}{text}{RESET}"

def is_prime(n: int) -> bool:
    """Check if a number is prime using Miller-Rabin or basic trial division."""
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    
    # Trial division for small numbers
    if n < 1000:
        i = 5
        while i * i <= n:
            if n % i == 0 or n % (i + 2) == 0:
                return False
            i += 6
        return True
        
    # Miller-Rabin Primality Test for larger numbers
    r, d = 0, n - 1
    while d % 2 == 0:
        r += 1
        d //= 2
    
    # 5 test rounds
    for _ in range(5):
        a = random.randint(2, n - 2)
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue
        for _ in range(r - 1):
            x = pow(x, 2, n)
            if x == n - 1:
                break
        else:
            return False
    return True

def get_prime_in_range(start: int, end: int) -> int:
    """Generate a random prime number in a range."""
    # Ensure range is valid
    if start >= end:
        start, end = end, start
    for _ in range(1000):
        val = random.randint(start, end)
        if is_prime(val):
            return val
    # Fallback to standard prime close to range
    for val in range(start, end):
        if is_prime(val):
            return val
    return 97 # Default small prime

def get_generators(p: int, limit: int = 10) -> List[int]:
    """Find a list of primitive roots (generators) modulo p."""
    if p == 2:
        return [1]
    
    # Factorize p - 1 (since the order of elements divides p-1)
    # Simple factorization for small-to-medium p
    factors = []
    n = p - 1
    d = 2
    while d * d <= n:
        if n % d == 0:
            factors.append(d)
            while n % d == 0:
                n //= d
        d += 1
    if n > 1:
        factors.append(n)
        
    generators = []
    # Test random elements
    for _ in range(100):
        g = random.randint(2, p - 1)
        # Check if g^(p-1)/f != 1 (mod p) for all prime factors f of p-1
        is_gen = True
        for f in factors:
            if pow(g, (p - 1) // f, p) == 1:
                is_gen = False
                break
        if is_gen and g not in generators:
            generators.append(g)
            if len(generators) >= limit:
                break
    return generators if generators else [2] # Fallback

def print_banner():
    print(colored("=" * 70, BOLD + CYAN))
    print(colored("      DIFFIE-HELLMAN KEY EXCHANGE SIMULATOR & EDUCATIONAL TOOL      ", BOLD + CYAN))
    print(colored("=" * 70, BOLD + CYAN))
    print("This tool visualizes the secure exchange of cryptographic keys over an")
    print("insecure channel, demonstrating Alice, Bob, and the eavesdropper Eve.")
    print("-" * 70)

def run_simulation(p: int, g: int, a: int, b: int, speed: float = 1.0):
    """Run a step-by-step key exchange simulation."""
    sleep_time = 1.5 * speed
    
    print(colored(f"\n[Step 1] Public Parameter Agreement", BOLD + YELLOW))
    print(f"Alice and Bob agree on two public numbers (usually generated by one party):")
    print(f"  - Prime Modulus (p)     = {colored(str(p), BOLD + CYAN)}")
    print(f"  - Generator/Base (g)    = {colored(str(g), BOLD + CYAN)}  (where g is a primitive root modulo p)")
    time.sleep(sleep_time)
    
    print(colored(f"\n[Step 2] Private Key Generation (Kept Secret)", BOLD + YELLOW))
    print(f"Both parties generate a random private key (never shared):")
    print(f"  - Alice's Private Key (a) = {colored(str(a), BOLD + MAGENTA)} (kept secret by Alice)")
    print(f"  - Bob's Private Key (b)   = {colored(str(b), BOLD + MAGENTA)} (kept secret by Bob)")
    time.sleep(sleep_time)
    
    print(colored(f"\n[Step 3] Calculate Public Keys", BOLD + YELLOW))
    print("Each party calculates their public key using: Public = (g ^ Private) mod p")
    
    # Alice computes A
    A = pow(g, a, p)
    print(f"  - Alice computes: A = ({g} ^ {a}) mod {p}")
    print(f"    Alice's Public Key (A)  = {colored(str(A), BOLD + GREEN)}")
    
    # Bob computes B
    B = pow(g, b, p)
    print(f"  - Bob computes:   B = ({g} ^ {b}) mod {p}")
    print(f"    Bob's Public Key (B)    = {colored(str(B), BOLD + GREEN)}")
    time.sleep(sleep_time)
    
    print(colored(f"\n[Step 4] Key Exchange (Publicly Transmitted)", BOLD + YELLOW))
    print("Alice and Bob exchange their public keys over the insecure channel.")
    print(colored("  >>> Alice sends A (" + str(A) + ") to Bob >>>", CYAN))
    print(colored("  <<< Bob sends B (" + str(B) + ") to Alice <<<", CYAN))
    time.sleep(sleep_time)
    
    print(colored(f"\n[Step 5] Calculate Shared Secret Key", BOLD + YELLOW))
    print("Each party computes the shared secret using the other party's public key:")
    print("  - Alice calculates: s = (B ^ a) mod p")
    s_alice = pow(B, a, p)
    print(f"    s = ({B} ^ {a}) mod {p} = {colored(str(s_alice), BOLD + RED)}")
    
    print("  - Bob calculates:   s = (A ^ b) mod p")
    s_bob = pow(A, b, p)
    print(f"    s = ({A} ^ {b}) mod {p} = {colored(str(s_bob), BOLD + RED)}")
    time.sleep(sleep_time)
    
    print(colored("\n" + "=" * 70, BOLD + GREEN))
    print(colored("  SUCCESS! Both parties successfully calculated the same shared key: " + str(s_alice), BOLD + GREEN))
    print(colored("=" * 70, BOLD + GREEN))
    time.sleep(sleep_time)
    
    # Show Eve's perspective
    print(colored("\n[Eavesdropper's (Eve) Perspective]", BOLD + RED))
    print("Eve intercepted all communications on the channel. Here is what everyone knows:")
    
    # Draw table
    row_format = "{:<22} | {:<22} | {:<22}"
    print(colored("-" * 70, BOLD))
    print(colored(row_format.format("Alice Knows", "Bob Knows", "Eve Knows (Intercepted)"), BOLD))
    print(colored("-" * 70, BOLD))
    print(row_format.format(f"p = {p} (Public)", f"p = {p} (Public)", f"p = {p} (Public)"))
    print(row_format.format(f"g = {g} (Public)", f"g = {g} (Public)", f"g = {g} (Public)"))
    print(row_format.format(f"a = {a} (Private)", f"b = {b} (Private)", "??? (Private Keys unknown)"))
    print(row_format.format(f"A = {A} (Mine)", f"B = {B} (Mine)", f"A = {A} (Intercepted)"))
    print(row_format.format(f"B = {B} (Received)", f"A = {A} (Received)", f"B = {B} (Intercepted)"))
    print(row_format.format(f"Shared Key = {s_alice}", f"Shared Key = {s_bob}", "Shared Key = ???"))
    print("-" * 70)
    
    print("To find the shared secret key, Eve must solve the Discrete Logarithm Problem:")
    print(f"  Find a or b such that: {g}^a mod {p} = {A}   OR   {g}^b mod {p} = {B}")
    print("For small numbers, this is easy. For large numbers (e.g. 2048-bit primes), it is")
    print("mathematically infeasible with current computer technology!")

def brute_force_discrete_log(g: int, A: int, p: int) -> Tuple[int, float, int]:
    """Attempt to solve the discrete logarithm problem by brute force."""
    start_time = time.time()
    steps = 0
    # Simple linear search (brute force)
    for x in range(1, p):
        steps += 1
        if pow(g, x, p) == A:
            elapsed = time.time() - start_time
            return x, elapsed, steps
    elapsed = time.time() - start_time
    return -1, elapsed, steps

def run_benchmark():
    """Demonstrate the complexity of brute forcing by scaling the prime size."""
    print(colored("\n=== Discrete Logarithm Brute-Force Scaling Demonstration ===", BOLD + YELLOW))
    print("This shows how increasing the size of the prime modulus (p) makes it exponentially")
    print("harder for an attacker (Eve) to break the key exchange by brute force.")
    print("-" * 70)
    
    # Test primes of various bit-lengths
    test_ranges = [
        ("~8-bit Prime", 100, 250),
        ("~12-bit Prime", 1000, 4000),
        ("~16-bit Prime", 30000, 65000),
        ("~20-bit Prime", 500000, 1000000),
    ]
    
    # Optional larger range if user wants to wait
    print(f"{'Prime Size':<15} | {'Prime Modulus (p)':<18} | {'Steps Taken':<12} | {'Time Elapsed':<15}")
    print("-" * 70)
    
    for label, r_start, r_end in test_ranges:
        p = get_prime_in_range(r_start, r_end)
        gens = get_generators(p, 1)
        g = gens[0]
        # Choose a random private key
        a = random.randint(2, p - 2)
        # Compute public key A
        A = pow(g, a, p)
        
        # Attack
        found_a, elapsed, steps = brute_force_discrete_log(g, A, p)
        
        time_str = f"{elapsed:.6f}s" if elapsed < 1.0 else f"{elapsed:.3f}s"
        print(f"{label:<15} | {p:<18} | {steps:<12} | {time_str:<15}")
        
    print("-" * 70)
    print("Note: In actual cryptosystems, prime sizes of 2048 bits or higher are used.")
    print("A 2048-bit prime has ~617 decimal digits. Brute forcing it would require testing")
    print("more states than there are atoms in the observable universe!")

def main():
    parser = argparse.ArgumentParser(description="Diffie-Hellman Key Exchange Simulator & Educational Visualizer")
    parser.add_argument("-p", type=int, help="Custom prime modulus (p). Must be prime.")
    parser.add_argument("-g", type=int, help="Custom base/generator (g). Must be primitive root modulo p.")
    parser.add_argument("-a", type=int, help="Custom private key for Alice (a).")
    parser.add_argument("-b", type=int, help="Custom private key for Bob (b).")
    parser.add_argument("--speed", type=float, default=1.0, help="Simulation speed multiplier (lower is faster, default 1.0)")
    parser.add_argument("--benchmark", action="store_true", help="Run brute-force scaling benchmark and exit")
    
    args = parser.parse_args()
    
    print_banner()
    
    if args.benchmark:
        run_benchmark()
        return
        
    # Set up or generate parameters
    p = args.p
    g = args.g
    
    if p is None:
        # Generate a friendly prime size for educational visualization (1000-5000)
        p = get_prime_in_range(1000, 5000)
        print(f"[*] Generated random prime modulus p = {p}")
    else:
        if not is_prime(p):
            print(colored(f"[!] Warning: {p} is not prime! The mathematics of DH require a prime modulus.", RED))
            sys.exit(1)
            
    if g is None:
        generators = get_generators(p)
        g = random.choice(generators)
        print(f"[*] Found primitive generator g = {g} for modulus {p}")
        
    a = args.a or random.randint(10, p - 2)
    b = args.b or random.randint(10, p - 2)
    
    # Adjust speed multiplier (inverse: 0.1 speed means sleep is 0.1 * duration)
    run_simulation(p, g, a, b, args.speed)

if __name__ == "__main__":
    main()
