#!/usr/bin/env python3
"""
gitignore_generator - Generate standard .gitignore files

A utility to generate high-quality .gitignore files for various programming languages,
frameworks, operating systems, and IDEs using the Toptal gitignore.io API,
with built-in offline fallbacks for common environments.

Usage:
    python tools/gitignore_generator.py [targets...] [options]

Options:
    -h, --help            Show this help message and exit
    -l, --list            List available/common gitignore templates
    -o OUTPUT, --output OUTPUT
                          Output file path (default: .gitignore)
    -a, --append          Append to the existing output file instead of overwriting
    --offline             Force offline mode using built-in templates
    targets               List of templates to combine (e.g. python vscode node)

Examples:
    python tools/gitignore_generator.py python vscode
    python tools/gitignore_generator.py rust windows --output .gitignore
    python tools/gitignore_generator.py node --append
"""

import argparse
import sys
import os
import urllib.request
import urllib.error
import json

# Common offline templates for major languages/IDEs/OSs
OFFLINE_TEMPLATES = {
    "python": """# Python Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/
cover/

# Translations
*.mo
*.pot

# Django stuff:
*.log
local_settings.py
db.sqlite3
db.sqlite3-journal

# Sphinx documentation
docs/_build/

# PyBuilder
.pybuilder/
target/

# Jupyter Notebook
.ipynb_checkpoints

# IPython
profile_default/
ipython_config.py

# environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/
""",
    "node": """# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-debug.log*

# Diagnostic reports
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate folders
.grunt

# Bower dependency directory
bower_components

# node-modules
node_modules/
jspm_packages/

# Snowpack dependency directory
web_modules/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variable files
.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# parcel-cache
.cache
.parcel-cache

# Next.js build images
.next
out

# Nuxt.js build project
.nuxt
dist

# Gatsby files
.cache/
public/

# Serverless Webpack directories
.webpack/

# Optional flow-typed directory
.flow-typed/

# expo env files
.env.local
.env.development.local
.env.test.local
.env.production.local
""" ,
    "go": """# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with `go test -c`
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

# Dependency directories (remove the comment if you want to git ignore vendor directory)
# vendor/

# Go workspace file
go.work
go.work.sum
""",
    "rust": """# Generated by Cargo
# will have compiled files and executables
debug/
target/

# Remove this line if you wish to associate your .cargo directory with the project
.cargo/

# These files contain project-specific settings
# and local developer configurations
Cargo.lock

# Backup files generated by rustfmt
**/*.rs.bk
""",
    "vscode": """.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
!.vscode/templates.json
*.code-workspace
.history/
""",
    "windows": """# Windows thumbnail cache files
Thumbs.db
ehthumbs.db
ehthumbs_vista.db

# Folder config file
Desktop.ini

# Recycle Bin used on file shares
$RECYCLE.BIN/

# Windows Shortcut files
*.lnk
""",
    "macos": """# General macOS files
.DS_Store
.AppleDouble
.LSOverride

# Icon must end with two carriage returns
Icon\r\r

# Thumbnails
._*

# Files that may be created by the Finder
.DocumentRevisions-V1
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Directories potentially created on external devices
.apdisk
"""
}

API_URL = "https://www.toptal.com/developers/gitignore/api"

def get_online_targets():
    """Fetch the list of all supported targets from gitignore.io."""
    try:
        req = urllib.request.Request(
            f"{API_URL}/list?format=json",
            headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
        )
        with urllib.request.urlopen(req, timeout=5) as response:
            data = response.read().decode('utf-8')
            # The API returns a JSON list or a comma-separated text
            if data.startswith('{') or data.startswith('['):
                return json.loads(data)
            else:
                # Comma separated / newline separated targets
                targets = []
                for line in data.split('\n'):
                    targets.extend([t.strip().lower() for t in line.split(',') if t.strip()])
                return sorted(list(set(targets)))
    except Exception as e:
        print(f"Warning: Failed to fetch online targets list: {e}. Using offline targets.", file=sys.stderr)
        return sorted(list(OFFLINE_TEMPLATES.keys()))

def generate_gitignore(targets, offline=False):
    """Generate gitignore content for the specified targets."""
    content = []
    
    if offline:
        print("Using offline mode...", file=sys.stderr)
        for target in targets:
            target_lower = target.lower()
            if target_lower in OFFLINE_TEMPLATES:
                content.append(f"### {target} (Offline Template) ###\n" + OFFLINE_TEMPLATES[target_lower])
            else:
                print(f"Warning: Offline template for '{target}' not found. Skipping.", file=sys.stderr)
        return "\n".join(content)
        
    try:
        targets_str = ",".join(targets)
        url = f"{API_URL}/{targets_str}"
        req = urllib.request.Request(
            url,
            headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
        )
        print(f"Fetching .gitignore for: {targets_str}...", file=sys.stderr)
        with urllib.request.urlopen(req, timeout=8) as response:
            return response.read().decode('utf-8')
    except urllib.error.URLError as e:
        print(f"Network error: {e}. Falling back to offline templates.", file=sys.stderr)
        # Attempt fallback
        return generate_gitignore(targets, offline=True)
    except Exception as e:
        print(f"Unexpected error fetching from API: {e}. Falling back to offline templates.", file=sys.stderr)
        return generate_gitignore(targets, offline=True)

def main():
    parser = argparse.ArgumentParser(
        description="Generate standard .gitignore files from gitignore.io or offline templates."
    )
    parser.add_argument('targets', nargs='*', help='Templates to generate (e.g. python vscode)')
    parser.add_argument('-l', '--list', action='store_true', help='List common / supported templates')
    parser.add_argument('-o', '--output', default='.gitignore', help='Output file path (default: .gitignore)')
    parser.add_argument('-a', '--append', action='store_true', help='Append to output file instead of overwriting')
    parser.add_argument('--offline', action='store_true', help='Force offline mode using built-in templates')
    
    args = parser.parse_args()
    
    if args.list:
        if args.offline:
            print("Common Offline Templates:")
            for t in sorted(OFFLINE_TEMPLATES.keys()):
                print(f"  - {t}")
        else:
            print("Fetching supported templates list...")
            targets = get_online_targets()
            print("\nSupported gitignore templates (total: {}):".format(len(targets)))
            
            # Print in columns
            cols = 4
            for i in range(0, len(targets), cols):
                chunk = targets[i:i+cols]
                print("".join(f"{t:<20}" for t in chunk))
        return 0
        
    if not args.targets:
        parser.print_help()
        return 1
        
    content = generate_gitignore(args.targets, offline=args.offline)
    
    if not content.strip():
        print("Error: No valid content was generated.", file=sys.stderr)
        return 1
        
    mode = 'a' if args.append else 'w'
    action_str = "Appending to" if args.append else "Writing to"
    
    try:
        with open(args.output, mode, encoding='utf-8') as f:
            if args.append and os.path.exists(args.output) and os.path.getsize(args.output) > 0:
                f.write("\n\n")
            f.write(content)
        print(f"Success: {action_str} {args.output} for targets: {', '.join(args.targets)}")
        return 0
    except Exception as e:
        print(f"Error writing to output file: {e}", file=sys.stderr)
        return 1

if __name__ == "__main__":
    sys.exit(main())
