#!/usr/bin/env python3
"""
HTTP Archive (HAR) Analyzer
Parses .har files generated by browser DevTools network tab.
Provides detailed insights into resource sizes, load times, HTTP status codes,
domain statistics, slowest requests, and automated performance optimization suggestions.
"""

import argparse
import json
import os
import sys
from urllib.parse import urlparse

# ANSI Colors for terminal output
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
BLUE = "\033[94m"
CYAN = "\033[96m"
BOLD = "\033[1m"
END = "\033[0m"

def format_size(size_bytes):
    """Formats bytes to human readable format."""
    if size_bytes is None or size_bytes < 0:
        return "0 B"
    for unit in ['B', 'KB', 'MB', 'GB']:
        if size_bytes < 1024.0:
            return f"{size_bytes:.2f} {unit}"
        size_bytes /= 1024.0
    return f"{size_bytes:.2f} TB"

def format_time(ms):
    """Formats milliseconds to human readable format."""
    if ms is None or ms < 0:
        return "0 ms"
    if ms < 1000.0:
        return f"{ms:.0f} ms"
    return f"{ms / 1000.0:.2f} s"

def get_mime_category(mime_type):
    """Categorizes MIME types into broader resource categories."""
    if not mime_type:
        return "Other"
    mime_type = mime_type.lower()
    if "html" in mime_type:
        return "Document (HTML)"
    elif "javascript" in mime_type or "ecmascript" in mime_type or mime_type.endswith("/js"):
        return "Script (JS)"
    elif "css" in mime_type:
        return "Stylesheet (CSS)"
    elif "image/" in mime_type:
        return "Image"
    elif "font/" in mime_type or "woff" in mime_type or "otf" in mime_type or "ttf" in mime_type:
        return "Font"
    elif "json" in mime_type or "xml" in mime_type:
        return "Data (JSON/XML)"
    elif "audio/" in mime_type or "video/" in mime_type:
        return "Media"
    return "Other"

def analyze_har(har_path, sort_by="time", limit=10):
    """Parses and analyzes the HAR file."""
    if not os.path.exists(har_path):
        print(f"{RED}[ERROR] HAR file not found: {har_path}{END}", file=sys.stderr)
        return None

    try:
        with open(har_path, "r", encoding="utf-8", errors="ignore") as f:
            data = json.load(f)
    except Exception as e:
        print(f"{RED}[ERROR] Failed to parse HAR JSON: {e}{END}", file=sys.stderr)
        return None

    log_data = data.get("log", {})
    entries = log_data.get("entries", [])
    if not entries:
        print(f"{YELLOW}[WARNING] No network entries found in HAR file.{END}")
        return None

    # Performance counters
    total_requests = len(entries)
    total_bytes_sent = 0
    total_bytes_received = 0
    total_resource_size = 0
    
    status_codes = {}
    methods = {}
    categories = {}
    domains = {}
    
    slowest_requests = []
    largest_requests = []
    
    # Audit lists
    uncompressed_text_assets = []
    missing_cache_headers = []
    error_responses = []
    redirect_chains = []

    for entry in entries:
        req = entry.get("request", {})
        res = entry.get("response", {})
        timings = entry.get("timings", {})
        
        url = req.get("url", "")
        parsed_url = urlparse(url)
        domain = parsed_url.netloc or "unknown"
        method = req.get("method", "GET")
        status = res.get("status", 0)
        
        # Timing
        duration = entry.get("time", 0.0) # in ms
        
        # Sizes
        req_header_size = req.get("headersSize", 0)
        if req_header_size < 0: req_header_size = 0
        req_body_size = req.get("bodySize", 0)
        if req_body_size < 0: req_body_size = 0
        
        res_header_size = res.get("headersSize", 0)
        if res_header_size < 0: res_header_size = 0
        res_body_size = res.get("bodySize", 0)
        if res_body_size < 0: res_body_size = 0
        
        content = res.get("content", {})
        res_decompressed_size = content.get("size", 0)
        mime_type = content.get("mimeType", "")
        
        # Accumulators
        total_bytes_sent += req_header_size + req_body_size
        total_bytes_received += res_header_size + res_body_size
        total_resource_size += res_decompressed_size
        
        # Status code counting
        status_codes[status] = status_codes.get(status, 0) + 1
        methods[method] = methods.get(method, 0) + 1
        
        # Domain stats
        domain_stats = domains.setdefault(domain, {"count": 0, "size": 0, "time": 0.0})
        domain_stats["count"] += 1
        domain_stats["size"] += res_body_size
        domain_stats["time"] += duration

        # MIME categorizing
        cat = get_mime_category(mime_type)
        cat_stats = categories.setdefault(cat, {"count": 0, "size": 0})
        cat_stats["count"] += 1
        cat_stats["size"] += res_body_size

        # For slowest and largest tracking
        slowest_requests.append((url, duration, method, status))
        largest_requests.append((url, res_body_size, method, status, res_decompressed_size))

        # Check headers
        headers_dict = {h.get("name", "").lower(): h.get("value", "") for h in res.get("headers", [])}
        content_encoding = headers_dict.get("content-encoding", "").lower()
        cache_control = headers_dict.get("cache-control", "").lower()
        expires = headers_dict.get("expires", "").lower()

        # 1. Error audit
        if status >= 400:
            error_responses.append((url, status, method))
            
        # 2. Redirect audit
        if 300 <= status < 400:
            redirect_chains.append((url, status, headers_dict.get("location", "unknown")))

        # 3. Compression audit for text-like resources (HTML, JS, CSS, JSON, XML, SVG)
        is_text = any(t in mime_type.lower() for t in ["html", "javascript", "css", "json", "xml", "svg"])
        if is_text and res_body_size > 2048: # > 2KB
            if not any(enc in content_encoding for enc in ["gzip", "br", "deflate"]):
                uncompressed_text_assets.append((url, mime_type, res_body_size))

        # 4. Cache Audit (specifically for static assets: JS, CSS, Images, Fonts)
        is_static = cat in ["Script (JS)", "Stylesheet (CSS)", "Image", "Font"]
        if is_static and status == 200:
            if not cache_control or "no-store" in cache_control or "no-cache" in cache_control:
                if not expires:
                    missing_cache_headers.append((url, cat, cache_control or "None"))

    # Sort slowest and largest
    slowest_requests.sort(key=lambda x: x[1], reverse=True)
    largest_requests.sort(key=lambda x: x[1], reverse=True)

    return {
        "total_requests": total_requests,
        "total_bytes_sent": total_bytes_sent,
        "total_bytes_received": total_bytes_received,
        "total_resource_size": total_resource_size,
        "status_codes": status_codes,
        "methods": methods,
        "categories": categories,
        "domains": domains,
        "slowest_requests": slowest_requests[:limit],
        "largest_requests": largest_requests[:limit],
        "uncompressed_text_assets": uncompressed_text_assets,
        "missing_cache_headers": missing_cache_headers,
        "error_responses": error_responses,
        "redirect_chains": redirect_chains
    }

def print_terminal_report(report, limit=10):
    """Outputs the HAR analysis report to the console."""
    if not report:
        return

    # Set up console sizing / spacing
    print(f"\n{BOLD}{CYAN}=" * 80)
    print(f"HAR ARCHIVE PERFORMANCE SUMMARY")
    print(f"=" * 80 + END)

    # General Info
    print(f"{BOLD}Total Requests:{END}       {report['total_requests']}")
    print(f"{BOLD}Total Data Sent:{END}      {format_size(report['total_bytes_sent'])} (Headers + Body)")
    print(f"{BOLD}Total Data Received:{END}  {format_size(report['total_bytes_received'])} (Wire size)")
    print(f"{BOLD}Total Uncompressed:{END}   {format_size(report['total_resource_size'])} (Decompressed assets)")
    if report['total_bytes_received'] > 0:
        ratio = report['total_resource_size'] / report['total_bytes_received']
        print(f"{BOLD}Compression Ratio:{END}   {ratio:.2f}x average saving")

    # Status Code Breakdown
    print(f"\n{BOLD}{CYAN}--- HTTP Status Code Breakdown ---{END}")
    for code, count in sorted(report["status_codes"].items()):
        color = GREEN if 200 <= code < 300 else (YELLOW if 300 <= code < 400 else RED)
        print(f"  Status {color}{code}{END}: {count} requests ({count/report['total_requests']*100:.1f}%)")

    # Resource Category Breakdown
    print(f"\n{BOLD}{CYAN}--- Resource Type Breakdown ---{END}")
    print(f"  {BOLD}{'Category':<20} | {'Count':<6} | {'Wire Size':<12} | {'Percentage':<10}{END}")
    print("  " + "-" * 57)
    for cat, stats in sorted(report["categories"].items(), key=lambda x: x[1]["size"], reverse=True):
        pct = (stats["size"] / report["total_bytes_received"] * 100) if report["total_bytes_received"] > 0 else 0
        print(f"  {cat:<20} | {stats['count']:<6} | {format_size(stats['size']):<12} | {pct:.1f}%")

    # Top Domains
    print(f"\n{BOLD}{CYAN}--- Top Domains by Data Transferred ---{END}")
    print(f"  {BOLD}{'Domain':<40} | {'Requests':<8} | {'Data':<12} | {'Total Latency':<12}{END}")
    print("  " + "-" * 79)
    sorted_domains = sorted(report["domains"].items(), key=lambda x: x[1]["size"], reverse=True)[:5]
    for domain, stats in sorted_domains:
        print(f"  {domain[:40]:<40} | {stats['count']:<8} | {format_size(stats['size']):<12} | {format_time(stats['time']):<12}")

    # Slowest Requests
    print(f"\n{BOLD}{RED}--- Top {limit} Slowest Requests ---{END}")
    for i, (url, time, method, status) in enumerate(report["slowest_requests"], 1):
        color = GREEN if 200 <= status < 300 else (YELLOW if 300 <= status < 400 else RED)
        short_url = url[:65] + "..." if len(url) > 68 else url
        print(f"  {i:2d}. [{format_time(time):>8}] - {method:<4} {color}{status}{END} - {short_url}")

    # Largest Requests
    print(f"\n{BOLD}{RED}--- Top {limit} Largest Payload Requests ---{END}")
    for i, (url, size, method, status, decomp_size) in enumerate(report["largest_requests"], 1):
        color = GREEN if 200 <= status < 300 else (YELLOW if 300 <= status < 400 else RED)
        short_url = url[:65] + "..." if len(url) > 68 else url
        saving = f" (Decomp: {format_size(decomp_size)})" if decomp_size > size else ""
        print(f"  {i:2d}. [{format_size(size):>9}] - {method:<4} {color}{status}{END} - {short_url}{saving}")

    # Performance Recommendations
    print(f"\n{BOLD}{YELLOW}================================================================================{END}")
    print(f"{BOLD}{YELLOW}PERFORMANCE OPTIMIZATION SUGGESTIONS{END}")
    print(f"{BOLD}{YELLOW}================================================================================{END}")
    
    recommendations = 0

    if report["error_responses"]:
        recommendations += 1
        print(f"\n{RED}[!] Broken Links / API Failures ({len(report['error_responses'])} events):{END}")
        for url, status, method in report["error_responses"][:3]:
            print(f"  - {method} {status} to {url[:70]}")
        if len(report['error_responses']) > 3:
            print(f"  - ... and {len(report['error_responses']) - 3} more. Fix these HTTP errors immediately.")

    if report["uncompressed_text_assets"]:
        recommendations += 1
        print(f"\n{YELLOW}[!] Text Assets Missing Compression ({len(report['uncompressed_text_assets'])} files):{END}")
        print("  Enable Gzip or Brotli compression on the server to reduce load times for:")
        total_potential_saving = 0
        for url, mime, size in report["uncompressed_text_assets"][:4]:
            print(f"  - {mime:<25} ({format_size(size):>8}) - {url[:40]}")
            total_potential_saving += size
        if len(report['uncompressed_text_assets']) > 4:
            print(f"  - ... and {len(report['uncompressed_text_assets']) - 4} more files.")
            for _, _, size in report["uncompressed_text_assets"][4:]:
                total_potential_saving += size
        print(f"  {BOLD}Estimated network transfer reduction: ~{format_size(total_potential_saving * 0.7)}{END} (assuming 70% compression savings)")

    if report["missing_cache_headers"]:
        recommendations += 1
        print(f"\n{YELLOW}[!] Static Assets Missing Long-Term Caching ({len(report['missing_cache_headers'])} files):{END}")
        print("  Leverage browser caching by adding Cache-Control: max-age=31536000 headers for:")
        for url, cat, cache in report["missing_cache_headers"][:4]:
            print(f"  - {cat:<15} (Cache: {cache}) - {url[:50]}")
        if len(report['missing_cache_headers']) > 4:
            print(f"  - ... and {len(report['missing_cache_headers']) - 4} more files.")

    if report["redirect_chains"]:
        recommendations += 1
        print(f"\n{CYAN}[i] Unnecessary HTTP Redirects ({len(report['redirect_chains'])} redirects):{END}")
        print("  Update links to point directly to destination endpoints to remove latency overhead:")
        for url, status, target in report["redirect_chains"][:3]:
            print(f"  - {status} redirect from {url[:35]} -> {target[:35]}")
        if len(report["redirect_chains"]) > 3:
            print(f"  - ... and {len(report['redirect_chains']) - 3} more.")

    if recommendations == 0:
        print(f"\n{GREEN}[✓] Excellent job! No major performance bottlenecks identified in caching or compression.{END}")
    print()

def generate_markdown_report(report, har_path, dest_path, limit=10):
    """Saves a Markdown file containing the analysis results."""
    try:
        with open(dest_path, "w", encoding="utf-8") as f:
            f.write(f"# HAR Performance Analysis Report\n\n")
            f.write(f"- **Source File:** `{os.path.basename(har_path)}`\n")
            f.write(f"- **Total Requests:** {report['total_requests']}\n")
            f.write(f"- **Total Payload Received:** {format_size(report['total_bytes_received'])}\n")
            f.write(f"- **Total Payload Sent:** {format_size(report['total_bytes_sent'])}\n\n")
            
            f.write(f"## Resource Breakdown\n\n")
            f.write(f"| Category | Count | Transferred Size |\n")
            f.write(f"|---|---|---|\n")
            for cat, stats in sorted(report["categories"].items(), key=lambda x: x[1]["size"], reverse=True):
                f.write(f"| {cat} | {stats['count']} | {format_size(stats['size'])} |\n")
            
            f.write(f"\n## Slowest Requests (Top {limit})\n\n")
            f.write(f"| # | Duration | Method | Status | URL |\n")
            f.write(f"|---|---|---|---|---|\n")
            for i, (url, time, method, status) in enumerate(report["slowest_requests"], 1):
                f.write(f"| {i} | {format_time(time)} | `{method}` | {status} | `{url}` |\n")

            f.write(f"\n## Largest Payload Requests (Top {limit})\n\n")
            f.write(f"| # | Wire Size | Method | Status | URL |\n")
            f.write(f"|---|---|---|---|---|\n")
            for i, (url, size, method, status, _) in enumerate(report["largest_requests"], 1):
                f.write(f"| {i} | {format_size(size)} | `{method}` | {status} | `{url}` |\n")

            f.write(f"\n## Performance Recommendations\n\n")
            
            if report["error_responses"]:
                f.write(f"### ❌ Broken Connections & HTTP Errors ({len(report['error_responses'])})\n")
                for url, status, method in report["error_responses"]:
                    f.write(f"- `{method} {status}`: {url}\n")
                f.write("\n")

            if report["uncompressed_text_assets"]:
                f.write(f"### ⚠️ Server Compression Missing ({len(report['uncompressed_text_assets'])})\n")
                f.write("Enable Gzip/Brotli on the server to compress the following files:\n\n")
                for url, mime, size in report["uncompressed_text_assets"]:
                    f.write(f"- `{url}` ({mime} - {format_size(size)})\n")
                f.write("\n")

            if report["missing_cache_headers"]:
                f.write(f"### ⚠️ Missing Cache-Control Headers ({len(report['missing_cache_headers'])})\n")
                f.write("Add long-term caching (`Cache-Control: max-age=31536000`) for these static assets:\n\n")
                for url, cat, cache in report["missing_cache_headers"]:
                    f.write(f"- `{url}` ({cat})\n")
                f.write("\n")

            if report["redirect_chains"]:
                f.write(f"### ℹ️ Redirect Overhead ({len(report['redirect_chains'])})\n")
                f.write("Avoid these redirects by linking directly to final targets:\n\n")
                for url, status, target in report["redirect_chains"]:
                    f.write(f"- `{status}` redirect: `{url}` -> `{target}`\n")
                f.write("\n")

        print(f"{GREEN}[✓] Markdown report successfully written to {dest_path}{END}")
    except Exception as e:
        print(f"{RED}[ERROR] Failed to save markdown report: {e}{END}", file=sys.stderr)

def main():
    parser = argparse.ArgumentParser(
        description="Browser HAR (HTTP Archive) Web Performance Analyzer."
    )
    parser.add_argument("har_file", help="Path to browser network HAR file")
    parser.add_argument("-s", "--sort", choices=["time", "size"], default="time",
                        help="Sort tables by 'time' (duration) or 'size' (default: 'time')")
    parser.add_argument("-n", "--limit", type=int, default=10,
                        help="Number of items to show in top lists (default: 10)")
    parser.add_argument("-o", "--output", help="Optional markdown output report file path")

    args = parser.parse_args()

    # Enable colored logs on Windows if supported
    if sys.platform == "win32":
        os.system("")

    report = analyze_har(args.har_file, sort_by=args.sort, limit=args.limit)
    if report:
        print_terminal_report(report, limit=args.limit)
        if args.output:
            generate_markdown_report(report, args.har_file, args.output, limit=args.limit)

if __name__ == "__main__":
    main()
