#!/usr/bin/env python3
"""
JSON Schema Generator - Infers a Draft-07 JSON Schema from a sample JSON file or payload.
"""

import argparse
import json
import sys
import os

def infer_type(val):
    """Infer JSON schema type from python value."""
    if val is None:
        return "null"
    elif isinstance(val, bool):
        return "boolean"
    elif isinstance(val, int):
        return "integer"
    elif isinstance(val, float):
        return "number"
    elif isinstance(val, str):
        return "string"
    elif isinstance(val, list):
        return "array"
    elif isinstance(val, dict):
        return "object"
    return "string"

def generate_schema(val, make_required=True):
    """Recursively generate schema details."""
    val_type = infer_type(val)
    schema = {"type": val_type}
    
    if val_type == "object":
        properties = {}
        required = []
        for k, v in val.items():
            properties[k] = generate_schema(v, make_required)
            if make_required:
                required.append(k)
        schema["properties"] = properties
        if required:
            schema["required"] = required
            
    elif val_type == "array":
        if not val:
            # Empty array, default to items matching any type
            schema["items"] = {}
        else:
            # Check if uniform or multiple types
            item_types = set(infer_type(item) for item in val)
            if len(item_types) == 1:
                # Uniform type
                sample_item = val[0]
                schema["items"] = generate_schema(sample_item, make_required)
            else:
                # Mixed types: use 'anyOf'
                schemas = []
                for t in item_types:
                    # Find first instance of that type to build schema
                    example = next(item for item in val if infer_type(item) == t)
                    schemas.append(generate_schema(example, make_required))
                schema["items"] = {"anyOf": schemas}
                
    return schema

def main():
    parser = argparse.ArgumentParser(description="JSON Schema Generator - Infer JSON Schema from sample data.")
    parser.add_argument("input_file", nargs="?", help="Input JSON file path (reads from stdin if omitted)")
    parser.add_argument("-o", "--output", help="Output schema file path (prints to stdout if omitted)")
    parser.add_argument("-p", "--pretty", action="store_true", default=True, help="Pretty print JSON output")
    parser.add_argument("--no-required", action="store_true", help="Do not include all fields in 'required' lists")
    parser.add_argument("-t", "--title", default="Generated Schema", help="Schema title")
    parser.add_argument("-d", "--description", default="Generated by JSON Schema Generator Tool", help="Schema description")
    
    args = parser.parse_args()
    
    # Read input
    if args.input_file:
        if not os.path.exists(args.input_file):
            print(f"Error: File '{args.input_file}' does not exist.", file=sys.stderr)
            sys.exit(1)
        try:
            with open(args.input_file, 'r', encoding='utf-8') as f:
                content = f.read()
        except Exception as e:
            print(f"Error reading file: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        content = sys.stdin.read()
        
    if not content.strip():
        print("Error: Input is empty.", file=sys.stderr)
        sys.exit(1)
        
    try:
        data = json.loads(content)
    except Exception as e:
        print(f"Error parsing input as JSON: {e}", file=sys.stderr)
        sys.exit(1)
        
    # Generate full schema wrapper
    schema = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": args.title,
        "description": args.description,
    }
    
    make_required = not args.no_required
    inferred = generate_schema(data, make_required)
    schema.update(inferred)
    
    indent = 4 if args.pretty else None
    output_str = json.dumps(schema, indent=indent)
    
    # Save or print
    if args.output:
        try:
            with open(args.output, 'w', encoding='utf-8') as f:
                f.write(output_str + '\n')
            print(f"Schema successfully saved to {args.output}")
        except Exception as e:
            print(f"Error writing schema to output file: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print(output_str)

if __name__ == "__main__":
    main()
