#!/usr/bin/env python3
"""
Python Script Bundler - Bundles a Python script and its local module dependencies into a single file.
Uses AST parsing to find local imports and embeds them with a custom module loader.

Usage:
    python tools/python_script_bundler.py ENTRY_SCRIPT [--output OUTPUT_SCRIPT]

Example:
    python tools/python_script_bundler.py tools/my_script.py -o dist/my_script_standalone.py
"""

import argparse
import ast
import os
import sys

def find_imports_in_file(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
        tree = ast.parse(content, filepath)
    except SyntaxError as e:
        print(f"[!] Syntax error parsing '{filepath}': {e}", file=sys.stderr)
        return []

    imports = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for name in node.names:
                imports.append(name.name)
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                imports.append(node.module)
    return imports


def resolve_module_path(module_name, base_dir):
    """
    Resolve a module import name to a local file path if it exists.
    Supports submodules and packages.
    """
    parts = module_name.split('.')
    current_path = base_dir
    
    for i, part in enumerate(parts):
        py_file = os.path.join(current_path, f"{part}.py")
        pkg_dir = os.path.join(current_path, part)
        pkg_init = os.path.join(pkg_dir, "__init__.py")
        
        if os.path.isfile(py_file):
            # Matches a single-file module
            return os.path.abspath(py_file), '.'.join(parts[:i+1]), False
        elif os.path.isdir(pkg_dir) and os.path.isfile(pkg_init):
            # Matches a package directory
            if i == len(parts) - 1:
                return os.path.abspath(pkg_init), '.'.join(parts), True
            current_path = pkg_dir
        else:
            break
            
    return None, None, None


def collect_dependencies(entry_path):
    base_dir = os.path.dirname(os.path.abspath(entry_path))
    
    todo = [os.path.abspath(entry_path)]
    visited = {os.path.abspath(entry_path)}
    
    modules = {}
    packages = set()
    
    while todo:
        curr_file = todo.pop(0)
        imported_names = find_imports_in_file(curr_file)
        
        for name in imported_names:
            res_file, res_name, is_pkg = resolve_module_path(name, base_dir)
            if res_file and res_file not in visited:
                visited.add(res_file)
                todo.append(res_file)
                
                try:
                    with open(res_file, 'r', encoding='utf-8', errors='ignore') as f:
                        source = f.read()
                    modules[res_name] = source
                    if is_pkg:
                        packages.add(res_name)
                    print(f"[*] Found local dependency: {res_name} -> {os.path.relpath(res_file)}")
                except Exception as e:
                    print(f"[!] Error reading '{res_file}': {e}", file=sys.stderr)
                    
    return modules, packages


def bundle_script(entry_path, output_path):
    print(f"[*] Analyzing entry script: {entry_path}")
    
    # 1. Collect all local dependency modules/packages
    modules, packages = collect_dependencies(entry_path)
    
    # 2. Read the primary entry script code
    try:
        with open(entry_path, 'r', encoding='utf-8', errors='ignore') as f:
            entry_code = f.read()
    except Exception as e:
        print(f"[!] Error reading entry script: {e}", file=sys.stderr)
        return False

    # 3. Construct the bundled header and loader logic
    loader_template = f"""# ==============================================================================
# Standalone Bundle Loader - Automatically Generated by Python Script Bundler
# ==============================================================================
import sys
import types
from importlib.machinery import ModuleSpec

class EmbeddedImporter:
    def __init__(self, modules, packages):
        self.modules = modules
        self.packages = packages

    def find_spec(self, fullname, path, target=None):
        if fullname in self.modules:
            is_pkg = fullname in self.packages
            spec = ModuleSpec(fullname, self, is_package=is_pkg)
            if is_pkg:
                spec.submodule_search_locations = []
            return spec
        return None

    def create_module(self, spec):
        return None

    def exec_module(self, module):
        fullname = module.__name__
        code_str = self.modules[fullname]
        code = compile(code_str, f"<embedded:{{fullname}}>", 'exec')
        if fullname in self.packages:
            module.__path__ = []
        exec(code, module.__dict__)

# Embedded Module Payload mapping
EMBEDDED_MODULES = {repr(k): repr(v) for k, v in modules.items()}
EMBEDDED_PACKAGES = {repr(list(packages))}

sys.meta_path.insert(0, EmbeddedImporter(EMBEDDED_MODULES, EMBEDDED_PACKAGES))

# ==============================================================================
# Original Entry Script Execution
# ==============================================================================
"""

    # We must format the dictionary and set generation carefully to avoid raw repr issues
    # Let's replace the placeholder strings with the actual JSON/Python dictionary literals
    embedded_modules_str = "{\n"
    for name, source in modules.items():
        # Encode source as safe string representation
        embedded_modules_str += f"    {repr(name)}: {repr(source)},\n"
    embedded_modules_str += "}"
    
    embedded_packages_str = "{" + ", ".join(repr(pkg) for pkg in packages) + "}"
    
    # Replace dictionary/set literals in template
    loader_code = loader_template.replace(
        "{repr(k): repr(v) for k, v in modules.items()}", embedded_modules_str
    ).replace(
        "{repr(list(packages))}", embedded_packages_str
    )
    
    # 4. Write out the combined payload
    try:
        out_dir = os.path.dirname(os.path.abspath(output_path))
        if out_dir:
            os.makedirs(out_dir, exist_ok=True)
            
        with open(output_path, 'w', encoding='utf-8') as f:
            # Preserve shebang if present in original entry script
            if entry_code.startswith('#!'):
                lines = entry_code.splitlines()
                f.write(lines[0] + '\n')
                f.write(loader_code)
                f.write('\n'.join(lines[1:]))
            else:
                f.write(loader_code)
                f.write(entry_code)
                
        print(f"[+] Bundle successfully created: {output_path}")
        return True
    except Exception as e:
        print(f"[!] Error writing bundle output: {e}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(description="Compile and Bundle a Python entrypoint and dependencies")
    parser.add_argument("entry", help="Main python script to bundle")
    parser.add_argument("-o", "--output", help="Output destination for standalone script (default: [entry]_bundled.py)")
    args = parser.parse_args()

    entry = args.entry
    if not os.path.isfile(entry):
        print(f"[!] Entry file '{entry}' does not exist.", file=sys.stderr)
        return 1
        
    output = args.output
    if not output:
        base, ext = os.path.splitext(entry)
        output = f"{base}_bundled{ext}"

    success = bundle_script(entry, output)
    return 0 if success else 1

if __name__ == "__main__":
    sys.exit(main())
