#!/usr/bin/env python3
"""
Self-Extracting Code Packer - Package directories into a single self-extracting Python script.

This tool recursively packs a directory tree (filtering out version control, caches, and virtual environments)
into an in-memory zip archive, encodes it using Base64, and wraps it inside a standalone Python script.
When the generated script is run, it extracts all files and reconstructs the directory structure.

Usage:
    python tools/self_extracting_packer.py <source_directory> -o <output_script.py> [--exclude EXCLUDE_PATTERNS]

Example:
    python tools/self_extracting_packer.py my_project -o run_my_project.py
"""

import argparse
import base64
import io
import os
import sys
import zipfile
from typing import List, Set

DEFAULT_EXCLUDES = {
    ".git",
    ".github",
    "__pycache__",
    ".venv",
    "venv",
    "node_modules",
    ".pytest_cache",
    ".idea",
    ".vscode",
    ".DS_Store",
}


def should_exclude(path: str, base_dir: str, exclude_list: Set[str]) -> bool:
    """Check if the given file or directory path matches any exclude patterns."""
    rel_path = os.path.relpath(path, base_dir)
    parts = rel_path.split(os.sep)
    for part in parts:
        if part in exclude_list or any(part.endswith(pat) for pat in exclude_list if pat.startswith("*")):
            return True
    return False


def pack_directory(source_dir: str, exclude_list: Set[str]) -> bytes:
    """Compress the directory contents into a ZIP file in memory and return its bytes."""
    mem_file = io.BytesIO()
    
    with zipfile.ZipFile(mem_file, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for root, dirs, files in os.walk(source_dir):
            # Modify dirs in-place to avoid walking down excluded directories
            dirs[:] = [d for d in dirs if not should_exclude(os.path.join(root, d), source_dir, exclude_list)]
            
            for file in files:
                file_path = os.path.join(root, file)
                if should_exclude(file_path, source_dir, exclude_list):
                    continue
                
                # Store with a relative path in the ZIP
                rel_path = os.path.relpath(file_path, source_dir)
                print(f"  Packing: {rel_path}")
                zip_file.write(file_path, rel_path)
                
    return mem_file.getvalue()


def generate_self_extractor(zip_bytes: bytes, source_dir: str) -> str:
    """Generate the Python self-extractor code containing the base64-encoded zip."""
    b64_data = base64.b64encode(zip_bytes).decode("utf-8")
    
    # Template for the self-extractor script
    template = f"""#!/usr/bin/env python3
# Standalone Self-Extracting Archive generated by Self-Extracting Code Packer.
# Original Directory: {os.path.basename(os.path.abspath(source_dir))}

import os
import io
import sys
import base64
import zipfile
import argparse

ARCHIVE_DATA = \"\"\"{b64_data}\"\"\"

def main():
    parser = argparse.ArgumentParser(description="Extract files from this standalone archive.")
    parser.add_argument("-o", "--output-dir", default=".", help="Directory to extract files into (default: current directory)")
    parser.add_argument("-l", "--list", action="store_true", help="List files in the archive without extracting")
    parser.add_argument("-y", "--yes", action="store_true", help="Automatically overwrite existing files without prompting")
    args = parser.parse_args()

    # Decode and load ZIP file from memory
    zip_bytes = base64.b64decode(ARCHIVE_DATA)
    zip_file = zipfile.ZipFile(io.BytesIO(zip_bytes))
    
    if args.list:
        print("Archive contents:")
        for name in zip_file.namelist():
            print(f"  {{name}}")
        return

    dest_dir = os.path.abspath(args.output_dir)
    os.makedirs(dest_dir, exist_ok=True)
    
    print(f"Extracting archive to: {{dest_dir}}")
    
    for name in zip_file.namelist():
        target_path = os.path.join(dest_dir, name)
        
        # Ensure target is not outside the output directory (Path Traversal prevention)
        real_target = os.path.realpath(target_path)
        real_dest = os.path.realpath(dest_dir)
        if not real_target.startswith(real_dest):
            print(f"Warning: Skipping suspicious path '{{name}}' (potential path traversal)")
            continue
            
        # Check if file already exists
        if os.path.exists(target_path) and not args.yes:
            response = input(f"File '{{name}}' already exists. Overwrite? [y/N]: ").lower()
            if not response.startswith('y'):
                print(f"  Skipped: {{name}}")
                continue
                
        # Create directories if necessary
        os.makedirs(os.path.dirname(target_path), exist_ok=True)
        
        # Extract file contents
        with open(target_path, "wb") as f:
            f.write(zip_file.read(name))
            
        print(f"  Extracted: {{name}}")

    print("\\nExtraction completed successfully!")

if __name__ == "__main__":
    main()
"""
    return template


def main():
    parser = argparse.ArgumentParser(description="Package a directory tree into a single self-extracting Python script.")
    parser.add_argument("source", help="The directory to package")
    parser.add_argument("-o", "--output", required=True, help="The path to save the generated self-extracting Python script")
    parser.add_argument("-e", "--exclude", action="append", help="Exclude pattern (can specify multiple times). Extends default exclusions.")
    
    args = parser.parse_args()
    
    if not os.path.isdir(args.source):
        print(f"Error: Source directory '{args.source}' does not exist or is not a directory.", file=sys.stderr)
        sys.exit(1)
        
    exclude_list = DEFAULT_EXCLUDES.copy()
    if args.exclude:
        exclude_list.update(args.exclude)
        
    print(f"Packing directory '{args.source}'...")
    print(f"Excluding folders/files: {', '.join(sorted(exclude_list))}")
    
    try:
        zip_bytes = pack_directory(args.source, exclude_list)
        print(f"Compressed size: {len(zip_bytes)} bytes")
        
        extractor_code = generate_self_extractor(zip_bytes, args.source)
        
        # Create parent directories for output if they don't exist
        os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
        
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(extractor_code)
            
        print(f"Successfully generated self-extracting script at: {args.output}")
        
    except Exception as e:
        print(f"Error occurred during packing: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
