#!/usr/bin/env python3
"""
SQLite Database Dumper - Export SQLite database schema and data as SQL statements.

This tool extracts schemas and table data from a local SQLite database file and
formats them as standard SQL statements. It runs entirely using standard library modules.
"""

import sys
import os
import sqlite3
import argparse
from datetime import datetime

# ANSI Colors
COLORS = {
    'green': '\033[32m',
    'yellow': '\033[33m',
    'red': '\033[31m',
    'cyan': '\033[36m',
    'bold': '\033[1m',
    'reset': '\033[0m'
}

def colorize(text, color):
    """Wrap text in ANSI color escape codes if output is a terminal"""
    if sys.stdout.isatty() and color in COLORS:
        return f"{COLORS[color]}{text}{COLORS['reset']}"
    return text

def log_info(msg):
    print(colorize(f"[*] {msg}", 'cyan'), file=sys.stderr)

def log_success(msg):
    print(colorize(f"[+] {msg}", 'green'), file=sys.stderr)

def log_error(msg):
    print(colorize(f"[-] Error: {msg}", 'red'), file=sys.stderr)

def escape_string(val):
    """Safely escape single quotes for SQL string literals."""
    if val is None:
        return 'NULL'
    return "'" + str(val).replace("'", "''") + "'"

def escape_value(val):
    """Format different Python datatypes for SQL INSERT statements."""
    if val is None:
        return 'NULL'
    elif isinstance(val, (int, float)):
        return str(val)
    elif isinstance(val, bytes):
        # Format BLOBs as X'hexstring'
        return f"X'{val.hex().upper()}'"
    else:
        return escape_string(val)

def dump_database(db_path, output_file=None, schema_only=False, data_only=False, tables=None):
    """
    Dumps the SQLite database schema and data to stdout or a file.
    """
    if not os.path.exists(db_path):
        log_error(f"Database file '{db_path}' does not exist.")
        return False

    try:
        conn = sqlite3.connect(db_path)
        conn.text_factory = lambda x: str(x, 'utf-8', 'replace')
        cursor = conn.cursor()
    except Exception as e:
        log_error(f"Failed to connect to database: {e}")
        return False

    out = sys.stdout
    if output_file:
        try:
            out = open(output_file, 'w', encoding='utf-8')
        except Exception as e:
            log_error(f"Failed to open output file: {e}")
            conn.close()
            return False

    # Header comments
    out.write(f"-- SQL Dump generated by SQLite Database Dumper\n")
    out.write(f"-- Database: {os.path.basename(db_path)}\n")
    out.write(f"-- Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    out.write(f"-- ------------------------------------------------------\n\n")
    out.write("PRAGMA foreign_keys=OFF;\n")
    out.write("BEGIN TRANSACTION;\n\n")

    try:
        # Fetch list of tables
        if tables:
            placeholders = ','.join('?' for _ in tables)
            query = f"SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name IN ({placeholders}) ORDER BY name;"
            cursor.execute(query, tables)
        else:
            query = "SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name;"
            cursor.execute(query)
        
        db_tables = cursor.fetchall()

        if not db_tables:
            log_info("No tables found matching criteria.")
        
        for table_name, create_sql in db_tables:
            if not create_sql:
                continue
            
            # 1. Write Table Schema
            if not data_only:
                out.write(f"--\n-- Table structure for table `{table_name}`\n--\n\n")
                out.write(f"DROP TABLE IF EXISTS `{table_name}`;\n")
                # Add semicolon if missing
                sql_stmt = create_sql.strip()
                if not sql_stmt.endswith(';'):
                    sql_stmt += ';'
                out.write(f"{sql_stmt}\n\n")
            
            # 2. Write Table Data
            if not schema_only:
                out.write(f"--\n-- Dumping data for table `{table_name}`\n--\n\n")
                
                # Get column info
                cursor.execute(f"PRAGMA table_info(`{table_name}`);")
                columns = [col[1] for col in cursor.fetchall()]
                cols_str = ", ".join(f"`{col}`" for col in columns)

                # Fetch rows
                cursor.execute(f"SELECT * FROM `{table_name}`;")
                rows = cursor.fetchall()
                
                if rows:
                    for row in rows:
                        vals_str = ", ".join(escape_value(val) for val in row)
                        out.write(f"INSERT INTO `{table_name}` ({cols_str}) VALUES ({vals_str});\n")
                    out.write("\n")
                else:
                    out.write(f"-- (No data found in table `{table_name}`)\n\n")

        # Dump views, indexes, triggers if not data_only
        if not data_only and not tables:
            # Views
            cursor.execute("SELECT name, sql FROM sqlite_master WHERE type='view' ORDER BY name;")
            views = cursor.fetchall()
            if views:
                out.write(f"--\n-- View structures\n--\n\n")
                for name, create_sql in views:
                    if create_sql:
                        out.write(f"DROP VIEW IF EXISTS `{name}`;\n")
                        sql_stmt = create_sql.strip()
                        if not sql_stmt.endswith(';'):
                            sql_stmt += ';'
                        out.write(f"{sql_stmt}\n\n")

            # Triggers
            cursor.execute("SELECT name, sql FROM sqlite_master WHERE type='trigger' ORDER BY name;")
            triggers = cursor.fetchall()
            if triggers:
                out.write(f"--\n-- Triggers\n--\n\n")
                for name, create_sql in triggers:
                    if create_sql:
                        out.write(f"DROP TRIGGER IF EXISTS `{name}`;\n")
                        sql_stmt = create_sql.strip()
                        if not sql_stmt.endswith(';'):
                            sql_stmt += ';'
                        out.write(f"{sql_stmt}\n\n")

            # Indexes
            cursor.execute("SELECT name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name;")
            indexes = cursor.fetchall()
            if indexes:
                out.write(f"--\n-- Indexes\n--\n\n")
                for name, create_sql in indexes:
                    sql_stmt = create_sql.strip()
                    if not sql_stmt.endswith(';'):
                        sql_stmt += ';'
                    out.write(f"{sql_stmt}\n\n")

        out.write("COMMIT;\n")
        out.write("PRAGMA foreign_keys=ON;\n")
        
        if output_file:
            out.close()
            log_success(f"Database successfully dumped to '{output_file}'")
        else:
            log_success("Database dump completed successfully.")
            
        return True

    except Exception as e:
        log_error(f"An error occurred while dumping the database: {e}")
        return False
    finally:
        conn.close()

def main():
    parser = argparse.ArgumentParser(
        description="SQLite Database Dumper - Exports SQLite schema & data as formatted SQL statement files.",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("db_path", help="Path to the SQLite database file to dump.")
    parser.add_argument(
        "-o", "--output", 
        help="Path to output file. If not specified, outputs to standard out."
    )
    
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--schema-only", 
        action="store_true", 
        help="Dump only the schema (table creation SQL), no rows."
    )
    group.add_argument(
        "--data-only", 
        action="store_true", 
        help="Dump only data (INSERT statements), no schema."
    )
    
    parser.add_argument(
        "-t", "--tables", 
        nargs="+", 
        help="List of specific tables to dump (dumps all by default)."
    )

    args = parser.parse_args()
    
    success = dump_database(
        db_path=args.db_path,
        output_file=args.output,
        schema_only=args.schema_only,
        data_only=args.data_only,
        tables=args.tables
    )
    
    return 0 if success else 1

if __name__ == "__main__":
    sys.exit(main())
