#!/usr/bin/env python3
"""
TOML to .Env Converter & Diff Tool
-----------------------------------
Converts TOML configuration files to .env environment files and vice versa with key flattening,
custom namespace prefixing, type casting annotations, and bi-directional diff comparison.

Author: Antigravity
License: MIT
"""

import sys
import os
import re
import json
import argparse
from typing import Dict, Any, List, Tuple, Optional

# ANSI Color Codes
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
BLUE = "\033[94m"
CYAN = "\033[96m"
BOLD = "\033[1m"
RESET = "\033[0m"

# Standard / Fallback TOML parser
try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        tomllib = None


def fallback_toml_parse(content: str) -> Dict[str, Any]:
    """
    Minimal naive TOML parser for basic tables, strings, numbers, and booleans.
    Fallback when tomllib/tomli is unavailable.
    """
    result: Dict[str, Any] = {}
    current_section = result
    
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
            
        if line.startswith('[') and line.endswith(']'):
            section_name = line[1:-1].strip()
            parts = section_name.split('.')
            curr = result
            for part in parts:
                if part not in curr or not isinstance(curr[part], dict):
                    curr[part] = {}
                curr = curr[part]
            current_section = curr
            continue
            
        if '=' in line:
            key, val = line.split('=', 1)
            key = key.strip()
            val = val.strip()
            
            # Basic type parsing
            if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
                parsed_val = val[1:-1]
            elif val.lower() == 'true':
                parsed_val = True
            elif val.lower() == 'false':
                parsed_val = False
            elif val.isdigit():
                parsed_val = int(val)
            elif re.match(r'^-?\d+\.\d+$', val):
                parsed_val = float(val)
            elif val.startswith('[') and val.endswith(']'):
                # Simple list parsing
                raw_items = val[1:-1].split(',')
                parsed_val = [i.strip().strip('"\'') for i in raw_items if i.strip()]
            else:
                parsed_val = val
                
            current_section[key] = parsed_val
            
    return result


def parse_toml_content(content: str) -> Dict[str, Any]:
    """Parse TOML string using tomllib if available, otherwise fallback parser."""
    if tomllib is not None:
        return tomllib.loads(content)
    return fallback_toml_parse(content)


def flatten_dict(d: Dict[str, Any], parent_key: str = '', sep: str = '_') -> Dict[str, Any]:
    """Recursively flatten nested dictionary into single-level dictionary with delimited keys."""
    items: List[Tuple[str, Any]] = []
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k.upper()}" if parent_key else k.upper()
        if isinstance(v, dict):
            items.extend(flatten_dict(v, new_key, sep=sep).items())
        else:
            items.append((new_key, v))
    return dict(items)


def env_value_to_string(val: Any) -> str:
    """Format Python values into valid .env line string representation."""
    if isinstance(val, bool):
        return "true" if val else "false"
    elif isinstance(val, (int, float)):
        return str(val)
    elif isinstance(val, (list, tuple)):
        return ",".join(str(item) for item in val)
    elif val is None:
        return ""
    else:
        s_val = str(val)
        if " " in s_val or "\n" in s_val or "#" in s_val or "=" in s_val:
            s_val = s_val.replace('"', '\\"')
            return f'"{s_val}"'
        return s_val


def parse_env_content(content: str) -> Dict[str, str]:
    """Parse .env file content into key-value map."""
    env_vars: Dict[str, str] = {}
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        if '=' in line:
            key, val = line.split('=', 1)
            key = key.strip()
            val = val.strip()
            if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
                val = val[1:-1]
            env_vars[key] = val
    return env_vars


def toml_to_env(toml_str: str, prefix: str = '', sep: str = '_') -> str:
    """Convert TOML string into formatted .env string."""
    data = parse_toml_content(toml_str)
    flat_data = flatten_dict(data, parent_key=prefix.upper() if prefix else '', sep=sep)
    
    lines = ["# Generated by toml_env_converter.py", ""]
    for k, v in sorted(flat_data.items()):
        val_str = env_value_to_string(v)
        lines.append(f"{k}={val_str}")
        
    return "\n".join(lines) + "\n"


def env_to_toml(env_str: str, sep: str = '_') -> str:
    """Convert .env content into formatted TOML string with nested tables."""
    env_vars = parse_env_content(env_str)
    nested: Dict[str, Any] = {}
    
    for key, val in env_vars.items():
        parts = key.lower().split(sep.lower())
        curr = nested
        for part in parts[:-1]:
            if part not in curr or not isinstance(curr[part], dict):
                curr[part] = {}
            curr = curr[part]
            
        leaf_key = parts[-1]
        # Infer type
        if val.lower() == 'true':
            curr[leaf_key] = True
        elif val.lower() == 'false':
            curr[leaf_key] = False
        elif val.isdigit():
            curr[leaf_key] = int(val)
        elif re.match(r'^-?\d+\.\d+$', val):
            curr[leaf_key] = float(val)
        else:
            curr[leaf_key] = val

    lines = ["# Generated by toml_env_converter.py", ""]
    
    # Root level keys
    root_keys = {k: v for k, v in nested.items() if not isinstance(v, dict)}
    for k, v in root_keys.items():
        if isinstance(v, bool):
            lines.append(f"{k} = {'true' if v else 'false'}")
        elif isinstance(v, (int, float)):
            lines.append(f"{k} = {v}")
        else:
            lines.append(f'{k} = "{v}"')
            
    # Tables
    tables = {k: v for k, v in nested.items() if isinstance(v, dict)}
    for table_name, table_data in tables.items():
        lines.append("")
        lines.append(f"[{table_name}]")
        for k, v in table_data.items():
            if isinstance(v, bool):
                lines.append(f"{k} = {'true' if v else 'false'}")
            elif isinstance(v, (int, float)):
                lines.append(f"{k} = {v}")
            else:
                lines.append(f'{k} = "{v}"')

    return "\n".join(lines) + "\n"


def diff_toml_and_env(toml_str: str, env_str: str, prefix: str = '', sep: str = '_') -> List[Dict[str, Any]]:
    """Compare TOML file against .env file and return differences."""
    toml_data = parse_toml_content(toml_str)
    flat_toml = flatten_dict(toml_data, parent_key=prefix.upper() if prefix else '', sep=sep)
    env_data = parse_env_content(env_str)
    
    diffs = []
    all_keys = sorted(set(flat_toml.keys()) | set(env_data.keys()))
    
    for key in all_keys:
        in_toml = key in flat_toml
        in_env = key in env_data
        
        if in_toml and not in_env:
            diffs.append({
                "key": key,
                "status": "MISSING_IN_ENV",
                "toml_val": flat_toml[key],
                "env_val": None
            })
        elif not in_toml and in_env:
            diffs.append({
                "key": key,
                "status": "MISSING_IN_TOML",
                "toml_val": None,
                "env_val": env_data[key]
            })
        else:
            t_val_str = env_value_to_string(flat_toml[key])
            e_val_str = env_data[key]
            if t_val_str != e_val_str:
                diffs.append({
                    "key": key,
                    "status": "VALUE_MISMATCH",
                    "toml_val": flat_toml[key],
                    "env_val": env_data[key]
                })
                
    return diffs


def main():
    parser = argparse.ArgumentParser(
        description="TOML to .Env Converter & Diff Tool",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  python tools/toml_env_converter.py --toml config.toml --out .env
  python tools/toml_env_converter.py --env .env --out config.toml
  python tools/toml_env_converter.py --diff --toml config.toml --env .env
"""
    )
    
    parser.add_argument("--toml", help="Path to input or comparison TOML file")
    parser.add_argument("--env", help="Path to input or comparison .env file")
    parser.add_argument("--out", help="Path to output file")
    parser.add_argument("--prefix", default="", help="Optional key prefix for .env generation")
    parser.add_argument("--sep", default="_", help="Separator for flattening keys (default: '_')")
    parser.add_argument("--diff", action="store_true", help="Compare TOML and .env files for differences")

    args = parser.parse_args()

    if args.diff:
        if not args.toml or not args.env:
            print(f"{RED}Error: Both --toml and --env must be specified for diff mode.{RESET}")
            sys.exit(1)
        with open(args.toml, 'r', encoding='utf-8') as f:
            t_content = f.read()
        with open(args.env, 'r', encoding='utf-8') as f:
            e_content = f.read()
            
        diffs = diff_toml_and_env(t_content, e_content, prefix=args.prefix, sep=args.sep)
        print(f"\n{BOLD}{CYAN}=== TOML vs .ENV Configuration Diff ==={RESET}\n")
        if not diffs:
            print(f"{GREEN}✓ Both configurations match perfectly!{RESET}\n")
        else:
            for d in diffs:
                st = d["status"]
                k = d["key"]
                if st == "MISSING_IN_ENV":
                    print(f"{YELLOW}[MISSING IN .ENV]{RESET} {BOLD}{k}{RESET} (TOML value: {d['toml_val']})")
                elif st == "MISSING_IN_TOML":
                    print(f"{RED}[MISSING IN TOML]{RESET} {BOLD}{k}{RESET} (.env value: {d['env_val']})")
                elif st == "VALUE_MISMATCH":
                    print(f"{BLUE}[VALUE MISMATCH]{RESET} {BOLD}{k}{RESET} (TOML: {d['toml_val']} | .env: {d['env_val']})")
            print(f"\nTotal differences found: {len(diffs)}")
        return

    if args.toml and not args.env:
        with open(args.toml, 'r', encoding='utf-8') as f:
            content = f.read()
        result = toml_to_env(content, prefix=args.prefix, sep=args.sep)
        if args.out:
            with open(args.out, 'w', encoding='utf-8') as f:
                f.write(result)
            print(f"{GREEN}✓ Converted {args.toml} -> {args.out}{RESET}")
        else:
            print(f"\n{BOLD}{CYAN}--- Generated .env Content ---{RESET}\n")
            print(result)

    elif args.env and not args.toml:
        with open(args.env, 'r', encoding='utf-8') as f:
            content = f.read()
        result = env_to_toml(content, sep=args.sep)
        if args.out:
            with open(args.out, 'w', encoding='utf-8') as f:
                f.write(result)
            print(f"{GREEN}✓ Converted {args.env} -> {args.out}{RESET}")
        else:
            print(f"\n{BOLD}{CYAN}--- Generated TOML Content ---{RESET}\n")
            print(result)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
